# numpy.ndarray

In [1]:
import numpy as np

In [7]:
a = np.arange(10)

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.ndim

1

In [10]:
a.shape

(10,)

In [11]:
a.size

10

In [13]:
A = np.ones(shape = (3,5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
a.ndim

1

In [15]:
A.ndim

2

In [16]:
A.size

15

In [17]:
A.shape

(3, 5)

In [19]:
X = np.array([[1,2,3],
             [2,3,4],
             [4,5,6]])
X

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [20]:
X.ndim

2

In [21]:
X.size

9

In [22]:
X.shape

(3, 3)

In [23]:
a = np.array([[1,2,3],
             [4,5]])
a

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [24]:
a.ndim

1

In [25]:
a.size

2

In [5]:
X = np.array([[1,2,3],
             [2,3,4],
             [4,5,6]])
X

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [4]:
import numpy as np

In [8]:
a = np.arange(10)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
a.reshape(-1,3)

ValueError: cannot reshape array of size 10 into shape (3)

In [15]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[0]

array([0, 1, 2, 3, 4])

In [17]:
X[-1]

array([10, 11, 12, 13, 14])

In [18]:
X[0]

array([0, 1, 2, 3, 4])

In [19]:
X[0][1]

1

In [20]:
X[(0,1)]

1

# 一维数组的切片操作

In [22]:
a = np.arange(10)

In [23]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[0:5]

array([0, 1, 2, 3, 4])

In [25]:
a[:5]

array([0, 1, 2, 3, 4])

In [26]:
a[5:]

array([5, 6, 7, 8, 9])

In [27]:
a[0:8:2]

array([0, 2, 4, 6])

In [28]:
a[::2]

array([0, 2, 4, 6, 8])

In [29]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 二维数组切片学习

In [32]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
X[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [45]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [48]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

# 引用关系

In [49]:
a = list(range(5))

In [50]:
a

[0, 1, 2, 3, 4]

In [51]:
b = a[0:2]

In [52]:
b

[0, 1]

In [53]:
b[1]=111

In [54]:
b

[0, 111]

In [56]:
a

[0, 1, 2, 3, 4]

In [57]:
X2 =X[:2,:2]

In [58]:
X2

array([[0, 1],
       [5, 6]])

In [59]:
X2[0,0] = 99

In [60]:
X2

array([[99,  1],
       [ 5,  6]])

In [61]:
X

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
X3 = X[:2,:2].copy()

In [63]:
X3[0,0] = 100

In [64]:
X3

array([[100,   1],
       [  5,   6]])

In [65]:
X

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])