# Numpy中arg运算

In [2]:
import numpy as np

In [7]:
np.random.seed(100)
x = np.random.random(50)
x

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333,
       0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375,
       0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045,
       0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497,
       0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ,
       0.74247969, 0.63018394, 0.58184219, 0.02043913, 0.21002658,
       0.54468488, 0.76911517, 0.25069523, 0.28589569, 0.85239509])

In [8]:
np.min(x)

0.004718856190972565

In [9]:
np.argmin(x)

4

In [10]:
x[4]

0.004718856190972565

In [14]:
x[36]

0.9809208570123115

In [15]:
np.max(x)

0.9809208570123115

In [17]:
ind = np.argwhere(x>0.5)
ind

array([[ 0],
       [ 3],
       [ 6],
       [ 7],
       [ 9],
       [10],
       [15],
       [16],
       [18],
       [21],
       [22],
       [28],
       [30],
       [31],
       [35],
       [36],
       [38],
       [39],
       [40],
       [41],
       [42],
       [45],
       [46],
       [49]], dtype=int64)

In [18]:
x[ind]

array([[0.54340494],
       [0.84477613],
       [0.67074908],
       [0.82585276],
       [0.57509333],
       [0.89132195],
       [0.97862378],
       [0.81168315],
       [0.81622475],
       [0.94002982],
       [0.81764938],
       [0.79566251],
       [0.59884338],
       [0.60380454],
       [0.89041156],
       [0.98092086],
       [0.89054594],
       [0.5769015 ],
       [0.74247969],
       [0.63018394],
       [0.58184219],
       [0.54468488],
       [0.76911517],
       [0.85239509]])

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.shuffle(x)
x

array([5, 6, 0, 1, 9, 8, 2, 7, 4, 3])

In [22]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(x)
x

array([1, 6, 3, 5, 4, 0, 2, 7, 8, 9])

In [26]:
ind = np.argsort(x)
ind

array([5, 0, 6, 2, 4, 3, 1, 7, 8, 9], dtype=int64)

In [27]:
x[ind]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[ind[:3]]

array([0, 1, 2])

In [31]:
x[ind[-3:]]

array([7, 8, 9])

In [32]:
np.partition(x,4)

array([0, 1, 3, 2, 4, 6, 5, 7, 8, 9])

# 二维数组的arg运算

In [35]:
X = np.random.randint(20,size=(4,5))
X

array([[ 2, 19, 17, 13,  5],
       [13,  3, 16, 12, 18],
       [13, 12,  3, 10,  8],
       [ 8, 12, 18, 12,  0]])

In [36]:
np.sort(X)

array([[ 2,  5, 13, 17, 19],
       [ 3, 12, 13, 16, 18],
       [ 3,  8, 10, 12, 13],
       [ 0,  8, 12, 12, 18]])

In [37]:
np.sort(X,axis=0)

array([[ 2,  3,  3, 10,  0],
       [ 8, 12, 16, 12,  5],
       [13, 12, 17, 12,  8],
       [13, 19, 18, 13, 18]])

In [38]:
np.argsort(X,axis=0)

array([[0, 1, 2, 2, 3],
       [3, 2, 1, 1, 0],
       [1, 3, 0, 3, 2],
       [2, 0, 3, 0, 1]], dtype=int64)