In [3]:
import numpy as np

# 一维数组的合并   concatenate

In [5]:
a = np.array([1,2,3])

In [6]:
b = np.array([4,5,6])

In [7]:
c = np.concatenate([a,b])

In [8]:
c

array([1, 2, 3, 4, 5, 6])

# 二维数组的合并  concatenate axis

In [13]:
A= np.arange(6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
B= np.arange(6,15).reshape(-1,3)
B

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
np.concatenate([A,B])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
#             年龄age，身高height
X1 = np.array ([
                [22,178],
                [23,175]
               ])
#             体重weight
X2 = np.array ([
                [50],
                [80]
               ])

In [27]:
X = np.concatenate([X1,X2],axis = 1)

In [28]:
X

array([[ 22, 178,  50],
       [ 23, 175,  80]])

# 一维数组与二维数组之间的合并  vstack   hstack

In [34]:
A = np.arange(4).reshape(-1,2)
A

array([[0, 1],
       [2, 3]])

In [40]:
a = np.arange(2)
a

array([0, 1])

In [41]:
np.concatenate([A,a.reshape(1,-1)])

array([[0, 1],
       [2, 3],
       [0, 1]])

In [42]:
np.vstack([A,a])

array([[0, 1],
       [2, 3],
       [0, 1]])

In [46]:
np.hstack([A,a.reshape(-1,1)])

array([[0, 1, 0],
       [2, 3, 1]])

# 一维数组的分割 分割  split

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.split(x,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [49]:
np.split(x,[3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [50]:
x1,x2,x3 = np.split(x,[3,7])

In [51]:
x1

array([0, 1, 2])

In [52]:
x3

array([7, 8, 9])

# 二维数组的分割 分割  split

In [56]:
A = np.arange(16).reshape(4,-1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
A1,A2 = np.split(A,[3])

In [58]:
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
A2

array([[12, 13, 14, 15]])

In [60]:
np.split(A,[3],axis=1)

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [65]:
np.split(A,[3],axis=0)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [67]:
#             体重weight
X1 = np.array ([
                [22,168,50,1],
                [18,163,80,1],
                [19,172,70,0]
               ])

In [68]:
np.hsplit(X1,[-1])

[array([[ 22, 168,  50],
        [ 18, 163,  80],
        [ 19, 172,  70]]), array([[1],
        [1],
        [0]])]

In [69]:
X,y = np.hsplit(X1,[-1])
X

array([[ 22, 168,  50],
       [ 18, 163,  80],
       [ 19, 172,  70]])

In [70]:
y

array([[1],
       [1],
       [0]])