In [2]:
import numpy as np
x = np.array(list('ABCDEFG'))
x

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1')

In [3]:
x[1]

'B'

In [4]:
x[1:5]

array(['B', 'C', 'D', 'E'], dtype='<U1')

In [5]:
x[1:5:2]

array(['B', 'D'], dtype='<U1')

In [6]:
[x[1],x[2],x[4]]

['B', 'C', 'E']

In [7]:
ind = [1,2,4]
x[ind]

array(['B', 'C', 'E'], dtype='<U1')

In [8]:
x

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1')

In [11]:
ind = np.arange(1,5).reshape(2,-1)
ind

array([[1, 2],
       [3, 4]])

In [13]:
x[ind]

array([['B', 'C'],
       ['D', 'E']], dtype='<U1')

In [16]:
X=np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
row = [0,1,3]
col = [1,2,3]
X[row,col]

array([ 1,  6, 15])

In [20]:
X[1,col]

array([5, 6, 7])

In [21]:
X[1:3,col]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [23]:
col = [True,True,False,False]
X[1:3,col]

array([[4, 5],
       [8, 9]])

In [24]:
x = np.arange(10)

In [25]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [27]:
x[x<5]

array([0, 1, 2, 3, 4])

In [28]:
x>=5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
x != 5

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [32]:
x-1 !=  x//2

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [34]:
id = (x+2 == x//2+3)
id

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [35]:
x[id]

array([1, 2])

In [36]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
X<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [38]:
x = x+2

In [39]:
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
X < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [42]:
np.sum(X<8)

8

In [43]:
np.count_nonzero(X<8)

8

In [44]:
np.count_nonzero(x<8)

6

In [45]:
np.any(x<2)

False

In [46]:
np.any(x<=2)

True

In [47]:
np.all(x>2)

False

In [48]:
np.all(x>=2)

True

In [49]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.sum(X%2==0)

8

In [51]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [52]:
np.sum(X%2==0,axis=1)

array([2, 2, 2, 2])

In [53]:
np.sum((X>2) & (X<10))

7

In [54]:
np.sum((X==2) | (X==10))

2

In [55]:
np.sum(~(X==2))

15

In [56]:
X[(X>2) & (X<10)]

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
X[:,-1]

array([ 3,  7, 11, 15])

In [58]:
X[:,-1]%3==0

array([ True, False, False,  True])

In [59]:
X[X[:,-1]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])