# Numpy得聚合操作

In [1]:
import numpy as np

In [3]:
x = np.random.random(100)
x

array([0.69017129, 0.9139012 , 0.63099678, 0.77101973, 0.81613984,
       0.34592062, 0.93823233, 0.91157296, 0.4587781 , 0.1821119 ,
       0.89521898, 0.12649449, 0.08886929, 0.1310994 , 0.44604656,
       0.94793258, 0.26066201, 0.91173889, 0.32343886, 0.85953069,
       0.87047684, 0.89532476, 0.83173715, 0.47736071, 0.42852547,
       0.0257046 , 0.96920431, 0.63761984, 0.91007543, 0.75002684,
       0.11955685, 0.88199476, 0.50513642, 0.47375028, 0.69986912,
       0.82627133, 0.87647655, 0.14484261, 0.52033039, 0.69041008,
       0.9875177 , 0.21598652, 0.70068642, 0.20091171, 0.04963385,
       0.34321125, 0.41272822, 0.44400943, 0.29815662, 0.3972578 ,
       0.4587093 , 0.98131886, 0.36103908, 0.15614446, 0.53856454,
       0.32041206, 0.86019439, 0.35282721, 0.0115427 , 0.51561642,
       0.66597655, 0.37317373, 0.0726553 , 0.67352864, 0.2827691 ,
       0.82521352, 0.41506929, 0.26398058, 0.87267131, 0.31411626,
       0.98941096, 0.36740678, 0.37794241, 0.33823881, 0.53125

In [4]:
sum(x)

53.521161395301405

In [5]:
np.sum(x)

53.521161395301405

In [7]:
arr = np.random.rand(10**7)

In [8]:
%timeit sum(arr)

751 ms ± 16.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit np.sum(arr)

12.4 ms ± 40.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
np.min(x)

0.01154269937741692

In [12]:
np.max(x)

0.9894109626454133

In [13]:
np.average(x)

0.5352116139530141

In [14]:
x.sum()

53.521161395301405

In [17]:
X =np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.sum(X)

120

In [19]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [20]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [21]:
np.prod(X)

0

In [22]:
np.prod(X+1)

2004189184

In [24]:
np.prod(X+1,axis =1)

array([   24,  1680, 11880, 43680])

In [25]:
np.mean(X)

7.5

In [26]:
np.mean(X,axis=0)

array([6., 7., 8., 9.])

In [27]:
np.median(X,axis=0)

array([6., 7., 8., 9.])

In [28]:
x =np.array([6600,5200,6300,5800,7100,90000])

In [29]:
np.mean(x)

20166.666666666668

In [30]:
np.median(x)

6450.0

In [31]:
np.percentile(x,q=50)

6450.0

In [32]:
np.percentile(x,q=100)

90000.0

In [33]:
np.max(x)

90000

In [34]:
for i in [0,25,50,75,100]:
    print(i,np.percentile(x,i))

0 5200.0
25 5925.0
50 6450.0
75 6975.0
100 90000.0


In [35]:
np.var(x)

975695555.5555555

In [36]:
np.sum((x - np.mean(x))**2)/np.size(x)

975695555.5555555

In [37]:
np.std(x)

31236.125808998073

In [38]:
np.var(x) ** 0.5

31236.125808998073

In [41]:
x = np.random.normal(0,1,size=1000000)

In [42]:
np.mean(x)

0.00036743607278018076

In [43]:
np.std(x)

1.001709129896656