In [1]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
range(10)

range(0, 10)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.array(range(5,10,2))

array([5, 7, 9])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [12]:
np.arange(2,20,5.5)

array([ 2. ,  7.5, 13. , 18.5])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros(shape = (3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full(10,99)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [23]:
np.full((3,5),99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [25]:
np.full((3,5),fill_value=99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [26]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [27]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [29]:
np.linspace(0,20,10,endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [30]:
np.random.randint(0,10)

2

In [31]:
np.random.randint(0,10)

9

In [32]:
np.random.randint(0,10)

9

In [33]:
np.random.randint(0,10,5)

array([1, 7, 1, 7, 8])

In [34]:
np.random.randint(0,10,size=5)

array([4, 1, 9, 7, 0])

In [35]:
np.random.randint(0,10,size=(3,5))

array([[3, 8, 7, 5, 7],
       [2, 1, 4, 2, 9],
       [1, 6, 5, 3, 7]])

In [36]:
np.random.seed(100)
np.random.randint(0,10,5)

array([8, 8, 3, 7, 7])

In [37]:
np.random.seed(100)
np.random.randint(0,10,5)

array([8, 8, 3, 7, 7])

In [38]:
np.random.seed(100)
np.random.randint(0,10,5)

array([8, 8, 3, 7, 7])

In [39]:
np.random.random()

0.5263824674842963

In [40]:
np.random.random(5)

array([0.14860484, 0.15671108, 0.18646718, 0.21010774, 0.4527399 ])

In [41]:
np.random.random((3,5))

array([[0.87014264, 0.06368104, 0.62431189, 0.52334774, 0.56229626],
       [0.00581719, 0.30742321, 0.95018431, 0.12665424, 0.07898787],
       [0.31135313, 0.63238359, 0.69935892, 0.64196495, 0.92002378]])

In [42]:
np.random.normal(size=5)

array([ 0.59829059, -1.75037385,  0.13330585, -1.31520994, -0.9374954 ])

In [43]:
np.random.normal(size=(3,5))

array([[ 0.38421144, -0.66167997,  2.58785597, -1.08310212, -2.06634065],
       [-1.27064503, -2.09572442, -2.13740639,  0.91584868,  0.59257575],
       [ 0.03795813,  0.37196757,  0.35975395, -0.14039647, -0.44373851]])