In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.1'

In [3]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
li[3]

3

In [5]:
li[3] = 33

In [6]:
li[3]

33

In [7]:
li

[0, 1, 2, 33, 4, 5, 6, 7, 8, 9]

In [8]:
li[5] = "Hello Python"

In [9]:
li[5]

'Hello Python'

In [10]:
import array
arr =array.array('i',list(range(10)))

In [11]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr =array.array('f',list(range(10)))
arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [13]:
arr[3] = 100

In [14]:
arr

array('f', [0.0, 1.0, 2.0, 100.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [15]:
# arr[5] = "Hello Python"   TypeError: must be real number, not str

TypeError: must be real number, not str

# numpy.ndarray

In [16]:
nparr = np.array(list(range(10)))

In [17]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
type(nparr)

numpy.ndarray

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr[3]

3

In [21]:
nparr[3] = 333

In [22]:
nparr[3]

333

In [23]:
nparr

array([  0,   1,   2, 333,   4,   5,   6,   7,   8,   9])

In [24]:
# nparr[5] = "Hello"    ValueError: invalid literal for int() with base 10: 'Hello'

ValueError: invalid literal for int() with base 10: 'Hello'

In [25]:
nparr[5] = 55.8

In [26]:
nparr

array([  0,   1,   2, 333,   4,  55,   6,   7,   8,   9])

In [27]:
nparr2 = np.array([1,2,3.0])

In [28]:
nparr2

array([1., 2., 3.])

In [29]:
nparr2 = np.array([1,2,3.0])

In [30]:
nparr2

array([1., 2., 3.])

In [31]:
nparr2.dtype

dtype('float64')

In [32]:
nparr3 = np.array([1,2,3],dtype=float)

In [33]:
nparr3.dtype

dtype('float64')

In [34]:
nparr3

array([1., 2., 3.])

In [35]:
def python_test(n):
    a=[i**2 for i in range(n)]
    b=[i**3 for i in range(n)]
    c = []
    for i in range(n):
        c.append(a[i]+b[i])
    return c

In [36]:
python_test(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [37]:
def numpy_test(n):
    a= np.arange(n) ** 2
    b= np.arange(n) ** 3
    c = a+b
    return c

In [38]:
numpy_test(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [39]:
%time res =python_test(10000000)

Wall time: 8.95 s


In [40]:
%time res =numpy_test(10000000)

Wall time: 284 ms
